name: 'toolsdotgo/sfm'
description: 'gets the desired version of the sfm binary'
inputs:
  version:
    description: 'desired sfm version'
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        vers="${{ inputs.version }}"
        [[ $vers == "" ]] && vers=$(curl https://api.github.com/repos/toolsdotgo/sfm/releases/latest | jq -r .tag_name)
        [[ $vers == "" ]] && { echo "couldn't get latest sfm version"; exit 1; }
        curl -L "https://github.com/toolsdotgo/sfm/releases/download/${vers}/sfm-linux-amd64-${vers}" > /usr/local/bin/sfm
        chmod +x /usr/local/bin/sfm
