name: 'toolsdotgo/sfm'
description: 'gets the desired version of the sfm binary'
inputs:
  version:
    description: 'desired sfm version'
    required: false
runs:
  using: "composite"
  steps:
    - run: wget "https://github.com/toolsdotgo/sfm/releases/download/${{ inputs.version }}/sfm-linux-amd64-${{ inputs.version }}" -O /usr/local/bin/sfm
      shell: bash
    - run: chmod +x /usr/local/bin/sfm
      shell: bash
