name: 'toolsdotgo/sfm'
description: 'gets the desired version of the sfm binary'
inputs:
  version:
    description: 'desired sfm version'
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        vers="${{ inputs.version }}"
        [[ $vers == "" ]] && vers=$(gh api repos/toolsdotgo/sfm/releases/latest --jq .tag_name)
        [[ $vers == "" ]] && { echo "couldn't get latest sfm version"; exit 1; }
        gh release download "${vers}" --repo toolsdotgo/sfm --pattern "sfm-linux-amd64-${vers}" --output /usr/local/bin/sfm
        chmod +x /usr/local/bin/sfm
      env:
        GITHUB_TOKEN: ${{ github.token }}
